mongodb:
  server:   localhost
  database: uptime
  user:     root 
  password: root 
  connectionString:       # alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:8082/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

server:
  port:     8082

plugins:
  - ./plugins/console
  - ./plugins/patternMatcher
  - ./plugins/httpOptions
  - ./plugins/email
  - ./plugins/basicAuth

email:
  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
  transport:         # see https://github.com/andris9/nodemailer for transport options
    service:   Gmail # see https://github.com/andris9/Nodemailer/blob/master/lib/wellknown.js for well-known services
    auth:            
      user:    'pulse.test.email@gmail.com'
      pass:    'pulse@123'
  event:
    up:        true
    down:      true
    paused:    false
    restarted: false
  message:           
    from:            'Status @GroupPlace <status@groupplace.com>' # The message sender, e.g. 'Fred Foo <foo@blurdybloop.com>'
    to:              'david.mcqueen@neudesic.com, dmcqueen@gmail.com, jesse.ezell@neudesic.com, brandon.bethke@neudesic.com, Jess.Sheneberger@neudesic.com' # The message recipient, e.g. 'bar@blurdybloop.com, baz@blurdybloop.com'
  dashboardUrl: 'http://status.groupplace.com'

basicAuth:
  username:    dash
  password:    pulse123
verbose: true # only used in dev
